language: ruby
rvm:
- 2.1
install:
  - gem install jekyll redcarpet pygments.rb jekyll-paginate jekyll-redirect-from html-proofer
script:
  - jekyll build
  - htmlproof _site
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
