# Site settings
title: cornernote
email: cornernote@gmail.com
url: https://cornernote.github.io
description: "Brett O'Donnell (aka cornernote) is an experienced web software developer specialising in PHP and MySQL."

# Social networks
social:
  - title: github
    url: https://github.com/cornernote
  - title: linkedin
    url: https://au.linkedin.com/in/mrphp/en

# Build settings
permalink: pretty
paginate_path: /blog/page:num
paginate: 20
excerpt_separator: <!--break-->
markdown: redcarpet
highlighter: pygments
exclude: ["README.md", "vendor"]
gems:
- jekyll-redirect-from

